# Adres URL do API.
@url = 

# Identyfikator typu komponentu.
@componentTypeId = 
# Identyfikator systemu operacyjnego.
@operatingSystemId = 
# Identyfikator oprgoramowania.
@softwareApplicationId = 

# Liczba elementów, które mają zostać zwrócone.
@count = 

### /configuration/component-types?count={count}
GET {{url}}/configuration/component-types?count={{count}}
Content-Type: application/json

### /configuration/component-types/count
GET {{url}}/configuration/component-types/count
Content-Type: application/json

### /configuration/component-types
POST {{url}}/configuration/component-types
Content-Type: application/json

{
    "Name": "",
    "Symbol": "",
    "Description": ""
}

### /configuration/component-types/{componentTypeId}
DELETE {{url}}/configuration/component-types/{{componentTypeId}}
Content-Type: application/json

### /configuration/component-types/{componentTypeId}
GET {{url}}/configuration/component-types/{{componentTypeId}}
Content-Type: application/json

### /configuration/operating-systems?count={count}
GET {{url}}/configuration/operating-systems?count={{count}}
Content-Type: application/json

### /configuration/operating-systems/count
GET {{url}}/configuration/operating-systems/count
Content-Type: application/json

### /configuration/operating-systems
POST {{url}}/configuration/operating-systems
Content-Type: application/json

{
    "Name": "",
    "Symbol": "",
    "Description": ""
}

### /configuration/operating-systems/{operatingSystemId}
DELETE {{url}}/configuration/operating-systems//{{operatingSystemId}}
Content-Type: application/json

### /configuration/operating-systems/{operatingSystemId}
GET {{url}}/configuration/operating-systems/{{operatingSystemId}}
Content-Type: application/json

### /configuration/software-applications?count={count}
GET {{url}}/configuration/software-applications?count={{count}}
Content-Type: application/json

### /configuration/software-applications/count
GET {{url}}/configuration/software-applications/count
Content-Type: application/json

### /configuration/software-applications
POST {{url}}/configuration/software-applications
Content-Type: application/json

{
    "Name": "",
    "Symbol": "",
    "Description": ""
}

### /configuration/software-applications/{softwareApplicationId}
DELETE {{url}}/configuration/software-applications/{{softwareApplicationId}}
Content-Type: application/json

### /configuration/software-applications/{softwareApplicationId}
GET {{url}}/configuration/software-applications/{{softwareApplicationId}}
Content-Type: application/json
