# Adres URL do API.
@url = 

# Identyfikator typu komponentu.
@componentTypeId = 
# Identyfikator systemu operacyjnego.
@operatingSystemId = 
# Identyfikator oprgoramowania.
@softwareApplicationId = 

### /configuration/component-types
GET {{url}}/configuration/component-types
Content-Type: application/json

### /configuration/component-types
POST {{url}}/configuration/component-types
Content-Type: application/json

{
    "Name": "",
    "Symbol": "",
    "Description": ""
}

### /configuration/component-types/{componentTypeId}
DELETE {{url}}/configuration/component-types/{{componentTypeId}}
Content-Type: application/json

### /configuration/component-types/{componentTypeId}
GET {{url}}/configuration/component-types/{{componentTypeId}}
Content-Type: application/json

### /configuration/operating-systems
GET {{url}}/configuration/operating-systems
Content-Type: application/json

### /configuration/operating-systems
POST {{url}}/configuration/operating-systems
Content-Type: application/json

{
    "Name": "",
    "Symbol": "",
    "Description": ""
}

### /configuration/operating-systems/{operatingSystemId}
DELETE {{url}}/configuration/operating-systems//{{operatingSystemId}}
Content-Type: application/json

### /configuration/operating-systems/{operatingSystemId}
GET {{url}}/configuration/operating-systems/{{operatingSystemId}}
Content-Type: application/json

### /configuration/software-application
GET {{url}}/configuration/software-application
Content-Type: application/json

### /configuration/software-application
POST {{url}}/configuration/software-application
Content-Type: application/json

{
    "Name": "",
    "Symbol": "",
    "Description": ""
}

### /configuration/software-application/{softwareApplicationId}
GET {{url}}/configuration/software-application/{{softwareApplicationId}}
Content-Type: application/json
