# Adres URL do API.
@url = 

# Identyfikator wdrożenia.
@implementationId = 
# Identyfikator środowiska.
@environmentId = 
# Identyfikator serwera.
@serverId = 

# Liczba elementów, które mają zostać zwrócone.
@count = 

### /implementations?count={count}
GET {{url}}/implementations?count={{count}}
Content-Type: application/json

### /implementations
POST {{url}}/implementations
Content-Type: application/json

{
    "Name": "",
    "Description": "",
    "ManagerId": ""
}

### /implementations/{implementationId}
DELETE {{url}}/implementations/{{implementationId}}
Content-Type: application/json

### /implementations/{implementationId}
GET {{url}}/implementations/{{implementationId}}
Content-Type: application/json

### /implementations/{implementationId}/environments
GET {{url}}/implementations/{{implementationId}}/environments
Content-Type: application/json

### /implementations/{implementationId}/environments
POST {{url}}/implementations/{{implementationId}}/environments
Content-Type: application/json

{
    "Name": "",
    "Symbol": "",
    "Description": "",
    "OperatorId": ""
}

### /implementations/{implementationId}/environments/{environmentId}
DELETE {{url}}/implementations/{{implementationId}}/environments/{{environmentId}}
Content-Type: application/json

### /implementations/{implementationId}/environments/{environmentId}
GET {{url}}/implementations/{{implementationId}}/environments/{{environmentId}}
Content-Type: application/json

### /implementations/{implementationId}/environments/{environmentId}/servers
GET {{url}}/implementations/{{implementationId}}/environments/{{environmentId}}/servers
Content-Type: application/json

### /implementations/{implementationId}/environments/{environmentId}/servers
POST {{url}}/implementations/{{implementationId}}/environments/{{environmentId}}/servers
Content-Type: application/json

{
    "Name": "",
    "Symbol": "",
    "IpAddress": "",
    "Description": "",
    "OperatingSystemId": ""
}

### /implementations/{implementationId}/environments/{environmentId}/servers/{serverId}
DELETE {{url}}/implementations/{{implementationId}}/environments/{{environmentId}}/servers/{{serverId}}
Content-Type: application/json

### /implementations/{implementationId}/environments/{environmentId}/servers/{serverId}
GET {{url}}/implementations/{{implementationId}}/environments/{{environmentId}}/servers/{{serverId}}
Content-Type: application/json

### /implementations/{implementationId}/environments/{environmentId}/servers/{serverId}/components
GET {{url}}/implementations/{{implementationId}}/environments/{{environmentId}}/servers/{{serverId}}/components
Content-Type: application/json

### /implementations/{implementationId}/environments/{environmentId}/servers/{serverId}/components
POST {{url}}/implementations/{{implementationId}}/environments/{{environmentId}}/servers/{{serverId}}/components
Content-Type: application/json

{
    "ComponentVersionId": ""
}

### /implementations/{implementationId}/environments/{environmentId}/servers/{serverId}/components
DELETE {{url}}/implementations/{{implementationId}}/environments/{{environmentId}}/servers/{{serverId}}/components
Content-Type: application/json

{
    "ComponentVersionId": ""
}

### /implementations/{implementationId}/environments/{environmentId}/servers/{serverId}/software-applications
GET {{url}}/implementations/{{implementationId}}/environments/{{environmentId}}/servers/{{serverId}}/software-applications
Content-Type: application/json

### /implementations/{implementationId}/environments/{environmentId}/servers/{serverId}/software-applications
POST {{url}}/implementations/{{implementationId}}/environments/{{environmentId}}/servers/{{serverId}}/software-applications
Content-Type: application/json

{
    "SoftwareApplicationId": ""
}

### /implementations/{implementationId}/environments/{environmentId}/servers/{serverId}/software-applications
DELETE {{url}}/implementations/{{implementationId}}/environments/{{environmentId}}/servers/{{serverId}}/software-applications
Content-Type: application/json

{
    "SoftwareApplicationId": ""
}
