# Adres URL do API.
@url = 

# Identyfikator komponentu.
@componentId = 
# Identyfikator środowiska.
@environmentId = 
# Identyfikator wdrożenia.
@implementationId = 
# Identyfikator produktu.
@productId = 

### /logs
GET {{url}}/logs
Content-Type: application/json

### /logs/components
GET {{url}}/logs/components
Content-Type: application/json

### /logs/components/{componentId}
GET {{url}}/logs/components/{{componentId}}
Content-Type: application/json

### /logs/environments
GET {{url}}/logs/environments
Content-Type: application/json

### /logs/environments/{environmentId}
GET {{url}}/logs/environments/{{environmentId}}
Content-Type: application/json

### /logs/implementations
GET {{url}}/logs/implementations
Content-Type: application/json

### /logs/implementations/{implementationId}
GET {{url}}/logs/implementations/{{implementationId}}
Content-Type: application/json

### /logs/products
GET {{url}}/logs/products
Content-Type: application/json

### /logs/products/{productId}
GET {{url}}/logs/products/{{productId}}
Content-Type: application/json
