# Adres URL do API.
@url = 

# Identyfikator produktu.
@productId = 
# Identyfikator komponentu.
@componentId = 
# Identyfikator wersji komponentu.
@componentVersionId = 

# Liczba elementów, które mają zostać zwrócone.
@count = 

### /products?count={count}
GET {{url}}/products?count={{count}}
Content-Type: application/json

### /products/tree
GET {{url}}/products/tree
Content-Type: application/json

### /products
POST {{url}}/products
Content-Type: application/json

{
    "Name": "",
    "Description": ""
}

### /products/{productId}
DELETE {{url}}/products/{{productId}}
Content-Type: application/json

### /products/{productId}
GET {{url}}/products/{{productId}}
Content-Type: application/json

### /products/{productId}/components
GET {{url}}/products/{{productId}}/components
Content-Type: application/json

### /products/{productId}/components
POST {{url}}/products/{{productId}}/components
Content-Type: application/json

{
    "Name": "",
    "SourceCodeRepositoryUrl": "",
    "Description": "",
    "ComponentTypeId": ""
}

### /products/{productId}/components/{componentId}
DELETE {{url}}/products/{{productId}}/components/{{componentId}}
Content-Type: application/json

### /products/{productId}/components/{componentId}
GET {{url}}/products/{{productId}}/components/{{componentId}}
Content-Type: application/json

### /products/{productId}/components/{componentId}/component-versions
GET {{url}}/products/{{productId}}/components/{{componentId}}/component-versions
Content-Type: application/json

### /products/{productId}/components/{componentId}/component-versions
POST {{url}}/products/{{productId}}/components/{{componentId}}/component-versions
Content-Type: application/json

{
    "ReleaseDate": "",
    "Major": 0,
    "Minor": 0,
    "Patch": 0,
    "Suffix": "",
    "Description": "",
    "IsImportant": false
}

### /products/{productId}/components/{componentId}/component-versions/{componentVersionId}
DELETE {{url}}/products/{{productId}}/components/{{componentId}}/component-versions/{{componentVersionId}}
Content-Type: application/json

### /products/{productId}/components/{componentId}/component-versions/{componentVersionId}
GET {{url}}/products/{{productId}}/components/{{componentId}}/component-versions/{{componentVersionId}}
Content-Type: application/json
