# Adres URL do API.
@url = 

# Identyfikator użytkownika.
@userId = 

### /users
GET {{url}}/users
Content-Type: application/json

### /users/administrators
GET {{url}}/users/administrators
Content-Type: application/json

### /users/administrators/count
GET {{url}}/users/administrators/count
Content-Type: application/json

### /users/administrators
POST {{url}}/users/administrators
Content-Type: application/json

{
    "FullName": "",
    "Login": "",
    "Phone": "",
    "Email": ""
}

### /users/developers
GET {{url}}/users/developers
Content-Type: application/json

### /users/developers/count
GET {{url}}/users/developers/count
Content-Type: application/json

### /users/developers
POST {{url}}/users/developers
Content-Type: application/json

{
    "FullName": "",
    "Login": "",
    "Phone": "",
    "Email": ""
}

### /users/managers
GET {{url}}/users/managers
Content-Type: application/json

### /users/managers/count
GET {{url}}/users/managers/count
Content-Type: application/json

### /users/managers
POST {{url}}/users/managers
Content-Type: application/json

{
    "FullName": "",
    "Login": "",
    "Phone": "",
    "Email": ""
}

### /users/operators
GET {{url}}/users/operators
Content-Type: application/json

### /users/operators/count
GET {{url}}/users/operators/count
Content-Type: application/json

### /users/operators
POST {{url}}/users/operators
Content-Type: application/json

{
    "FullName": "",
    "Login": "",
    "Phone": "",
    "Email": ""
}

### /users/{userId}
DELETE {{url}}/users/{{userId}}
Content-Type: application/json

### /users/{userId}
GET {{url}}/users/{{userId}}
Content-Type: application/json
